"""Apply official-RandOpt vLLM physical perturbations to a Transformers model.

The population search runs on vLLM, where decoder projections can be fused
(``qkv_proj`` and ``gate_up_proj``).  Functional displacement is measured with
the standard Transformers forward pass so attention is evaluated normally.
This bridge preserves the vLLM physical tensor as the unit of noise, norm, and
Modular scale, then slices that perturbation into the corresponding checkpoint
parameters.  Noise is generated by the official RandOpt rule: a fresh
generator receives the same candidate seed for every physical tensor.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Iterable, Mapping, Sequence

import torch

from utils.official_randopt_protocol import sample_parameter_noise
from utils.perturbation_norms import normalization_denominator


@dataclass(frozen=True)
class ParameterFragment:
    name: str
    start: int | None = None
    stop: int | None = None


@dataclass(frozen=True)
class PhysicalParameterBinding:
    physical_name: str
    shape: tuple[int, ...]
    role: str
    multiplicity: float
    modular_scale: float
    fragments: tuple[ParameterFragment, ...]


def _named_parameters(model) -> dict[str, torch.nn.Parameter]:
    try:
        rows = model.named_parameters(remove_duplicate=True)
    except TypeError:  # pragma: no cover - compatibility with older torch
        rows = model.named_parameters()
    parameters = dict(rows)
    language_prefix = "model.language_model."
    if any(name.startswith(language_prefix) for name in parameters):
        parameters = {
            name: parameter
            for name, parameter in parameters.items()
            if name.startswith(language_prefix) or name.startswith("lm_head.")
        }
    return parameters


def _hf_name_candidates(physical_name: str) -> tuple[str, ...]:
    """Return possible HF names for a language-only vLLM tensor."""

    candidates = [physical_name]
    if physical_name.startswith("language_model.model."):
        candidates.append(
            "model.language_model."
            + physical_name.removeprefix("language_model.model.")
        )
    elif physical_name.startswith("language_model."):
        candidates.append("model." + physical_name)
    elif physical_name.startswith("model."):
        candidates.append(
            "model.language_model." + physical_name.removeprefix("model.")
        )
    if physical_name.startswith("language_model.lm_head."):
        candidates.append("lm_head." + physical_name.removeprefix("language_model.lm_head."))
    return tuple(dict.fromkeys(candidates))


def _fused_fragment_names(physical_name: str) -> tuple[str, ...] | None:
    if "qkv_proj." in physical_name:
        return tuple(
            physical_name.replace("qkv_proj.", f"{projection}_proj.")
            for projection in ("q", "k", "v")
        )
    if "gate_up_proj." in physical_name:
        return tuple(
            physical_name.replace("gate_up_proj.", f"{projection}_proj.")
            for projection in ("gate", "up")
        )
    return None


def build_physical_parameter_bindings(
    model,
    runtime_rows: Sequence[Mapping[str, Any]],
) -> tuple[list[PhysicalParameterBinding], dict[str, torch.nn.Parameter]]:
    """Bind every vLLM physical parameter to one or more HF parameters.

    The function is intentionally strict: each HF parameter must be covered
    exactly once and each runtime shape must match the concatenated checkpoint
    shapes.  This catches tied-head, bias, and architecture-layout mistakes
    before a radius is measured.
    """

    parameters = _named_parameters(model)
    used: set[str] = set()
    bindings: list[PhysicalParameterBinding] = []

    for row in runtime_rows:
        physical_name = str(row["parameter_name"])
        shape = tuple(int(size) for size in row["shape"])
        direct_name = next(
            (name for name in _hf_name_candidates(physical_name) if name in parameters),
            None,
        )
        fused_names = None
        for candidate in _hf_name_candidates(physical_name):
            names = _fused_fragment_names(candidate)
            if names is not None and all(name in parameters for name in names):
                fused_names = names
                break

        if direct_name is not None:
            if tuple(parameters[direct_name].shape) != shape:
                raise ValueError(
                    f"Shape mismatch for {physical_name}: runtime={shape}, "
                    f"transformers={tuple(parameters[direct_name].shape)}"
                )
            fragments = (ParameterFragment(direct_name),)
        elif fused_names is not None:
            missing = [name for name in fused_names if name not in parameters]
            if missing:
                raise ValueError(
                    f"Cannot map fused runtime tensor {physical_name}; missing "
                    + ", ".join(missing)
                )
            part_shapes = [tuple(parameters[name].shape) for name in fused_names]
            if not shape or any(not part_shape for part_shape in part_shapes):
                raise ValueError(f"Fused tensor {physical_name} must be at least 1-D")
            if any(part_shape[1:] != shape[1:] for part_shape in part_shapes):
                raise ValueError(
                    f"Non-concatenated dimensions do not match for {physical_name}"
                )
            if sum(part_shape[0] for part_shape in part_shapes) != shape[0]:
                raise ValueError(
                    f"Concatenated first dimension does not match for {physical_name}: "
                    f"runtime={shape}, parts={part_shapes}"
                )
            offset = 0
            fragment_rows = []
            for name, part_shape in zip(fused_names, part_shapes):
                fragment_rows.append(
                    ParameterFragment(name=name, start=offset, stop=offset + part_shape[0])
                )
                offset += part_shape[0]
            fragments = tuple(fragment_rows)
        else:
            raise ValueError(
                f"No Transformers parameter matches runtime tensor {physical_name}"
            )

        for fragment in fragments:
            if fragment.name in used:
                raise ValueError(
                    f"Transformers parameter is mapped more than once: {fragment.name}"
                )
            used.add(fragment.name)

        bindings.append(
            PhysicalParameterBinding(
                physical_name=physical_name,
                shape=shape,
                role=str(row.get("role", "")),
                multiplicity=float(row.get("multiplicity", 1.0)),
                modular_scale=float(row.get("scale", float("inf"))),
                fragments=fragments,
            )
        )

    missing_from_runtime = sorted(set(parameters) - used)
    if missing_from_runtime:
        raise ValueError(
            "Transformers parameters absent from the vLLM perturbation layout: "
            + ", ".join(missing_from_runtime[:20])
        )
    return bindings, parameters


def binding_manifest(
    bindings: Iterable[PhysicalParameterBinding],
) -> list[Mapping[str, Any]]:
    return [
        {
            "parameter_name": binding.physical_name,
            "shape": list(binding.shape),
            "role": binding.role,
            "multiplicity": binding.multiplicity,
            "modular_scale": binding.modular_scale,
            "transformers_fragments": [
                {"name": row.name, "start": row.start, "stop": row.stop}
                for row in binding.fragments
            ],
        }
        for binding in bindings
    ]


def snapshot_parameters(
    parameters: Mapping[str, torch.nn.Parameter],
) -> dict[str, torch.Tensor]:
    return {
        name: parameter.detach().clone()
        for name, parameter in parameters.items()
    }


def initialize_condition_from_base(
    parameters: Mapping[str, torch.nn.Parameter],
    snapshot: Mapping[str, torch.Tensor],
) -> None:
    """Initialize one method/radius condition from the checkpoint state.

    This is called once before evaluating a complete candidate prefix.  It is
    not used between candidates; every candidate is restored by regenerating
    and subtracting its noise, as in official RandOpt.
    """

    with torch.no_grad():
        for name, parameter in parameters.items():
            parameter.copy_(snapshot[name])


def parameter_drift_summary(
    parameters: Mapping[str, torch.nn.Parameter],
    snapshot: Mapping[str, torch.Tensor],
) -> Mapping[str, float | int]:
    mismatched = 0
    max_abs_error = 0.0
    with torch.no_grad():
        for name, parameter in parameters.items():
            base = snapshot[name]
            if not torch.equal(parameter, base):
                mismatched += 1
                max_abs_error = max(
                    max_abs_error,
                    float((parameter.float() - base.float()).abs().max().item()),
                )
    return {
        "num_mismatched_parameters": mismatched,
        "max_abs_error": max_abs_error,
    }


def apply_physical_perturbation(
    *,
    bindings: Sequence[PhysicalParameterBinding],
    parameters: Mapping[str, torch.nn.Parameter],
    candidate_seed: int,
    radius: float,
    method: str,
    power_iterations: int,
    restore: bool = False,
) -> None:
    """Apply or subtract one official-RandOpt perturbation."""

    if not bindings:
        raise ValueError("at least one physical parameter binding is required")
    reference = parameters[bindings[0].fragments[0].name]
    with torch.no_grad():
        for binding in bindings:
            noise = sample_parameter_noise(
                binding.shape,
                dtype=reference.dtype,
                device=reference.device,
                candidate_seed=candidate_seed,
            )
            denominator = normalization_denominator(
                method=method,
                name=binding.physical_name,
                noise=noise,
                modular_scale=binding.modular_scale,
                power_iterations=power_iterations,
            )
            if denominator != float("inf"):
                alpha = float(radius) / float(denominator)
                if restore:
                    alpha *= -1.0
                for fragment in binding.fragments:
                    fragment_noise = (
                        noise
                        if fragment.start is None
                        else noise[fragment.start : fragment.stop]
                    )
                    parameters[fragment.name].add_(fragment_noise, alpha=alpha)
            del noise


__all__ = [
    "PhysicalParameterBinding",
    "ParameterFragment",
    "apply_physical_perturbation",
    "binding_manifest",
    "build_physical_parameter_bindings",
    "initialize_condition_from_base",
    "parameter_drift_summary",
    "snapshot_parameters",
]
