"""Stable sensitivity-calibrated recursive modular scaling for decoder LMs.

This revision fixes a failure mode in the original V2 implementation.  The
original implementation propagated measured residual/block sensitivities across
all decoder blocks.  Even after clipping, this creates products such as
``4 ** num_layers`` and can make late-layer perturbations catastrophically
large after global median matching.

The corrected implementation is deliberately *local-only*:

* Version-1 architecture and mass scales are the reference geometry.
* Calibrated sensitivities alter only relative scales *inside the same decoder
  block*.
* Decoder blocks, final normalization, and the output head expose unit
  sensitivity to the parent tree, so no depth-wise sensitivity product is
  formed.
* Each block's V2/V1 scale ratios are median-centered and clipped.  By default,
  every parameter scale remains within [0.5, 2.0] of its V1 scale.
* Measured residual and full-block Jacobians are retained as diagnostics only;
  they are not multiplied through depth.

The model forward pass remains unchanged and an existing V2 calibration profile
can be reused.  New profile fields are optional and older schema-version-2
profiles are interpreted with the safe local-only defaults.
"""

from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
import math
from pathlib import Path
import statistics
from typing import Any, Dict, Iterable, List, Mapping, MutableMapping, Sequence, Tuple

import torch

try:
    from utils.recursive_modular_v1 import (
        ModuleNode,
        ParameterSpec,
        RecursiveModularResult,
        _allocate_masses,
        build_recursive_modular_result,
        infer_parameter_spec,
        infer_qwen_parameter_spec,
    )
except ImportError:  # pragma: no cover
    from recursive_modular_v1 import (
        ModuleNode,
        ParameterSpec,
        RecursiveModularResult,
        _allocate_masses,
        build_recursive_modular_result,
        infer_parameter_spec,
        infer_qwen_parameter_spec,
    )

_EPS = 1e-12
_LOCAL_REQUIRED_LAYER_KEYS = (
    "input_norm",
    "post_attention_norm",
    "attention_module",
    "mlp_module",
)
_DIAGNOSTIC_LAYER_KEYS = (
    "attention_residual",
    "mlp_residual",
    "block",
)


@dataclass(frozen=True)
class V2ApplicationConfig:
    # Clipping used while interpreting measured module/linear sensitivities.
    clip_min: float = 0.25
    clip_max: float = 4.0
    factor_clip_min: float = 0.25
    factor_clip_max: float = 4.0
    linear_policy: str = "analytic"  # analytic | unit
    strict_profile: bool = True

    # Safe V2.1 behavior.
    propagation_mode: str = "local_only"
    local_normalization: str = "per_block_median"
    local_ratio_clip_min: float = 0.5
    local_ratio_clip_max: float = 2.0

    # Legacy fields are accepted for backward compatibility but ignored by the
    # local-only propagation rule.
    scale_normalization: str = "match_v1_median"
    block_reconciliation: str = "geometric"


def _jsonable(value: Any) -> Any:
    if isinstance(value, Mapping):
        return {str(key): _jsonable(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_jsonable(item) for item in value]
    if isinstance(value, (str, int, float, bool)) or value is None:
        return value
    raise TypeError(f"Sensitivity profile contains non-JSON value: {type(value)!r}")


def _extract_profile_scalar(raw: Any, path: str) -> float:
    if isinstance(raw, Mapping):
        if "value" not in raw:
            raise ValueError(f"Profile entry {path} must contain a 'value' field")
        raw = raw["value"]
    try:
        return float(raw)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"Profile entry {path} is not numeric: {raw!r}") from exc


def load_sensitivity_profile(value: object | None) -> Dict[str, Any] | None:
    """Load a mapping, JSON string, or JSON path.

    Schema-version-2 profiles generated by the original V2 calibrator remain
    valid.  Missing local-only application fields receive safe defaults.
    """

    if value is None:
        return None
    if isinstance(value, Mapping):
        parsed: Any = dict(value)
    elif isinstance(value, (str, Path)):
        path = Path(value).expanduser()
        if path.is_file():
            parsed = json.loads(path.read_text(encoding="utf-8"))
        elif isinstance(value, Path):
            raise FileNotFoundError(f"Sensitivity profile path does not exist: {path}")
        else:
            try:
                parsed = json.loads(value)
            except json.JSONDecodeError as exc:
                raise ValueError(
                    "sensitivity_profile must be a JSON object or a path to JSON"
                ) from exc
    else:
        raise TypeError(
            "sensitivity_profile must be None, mapping, JSON string, or path"
        )

    if not isinstance(parsed, Mapping):
        raise ValueError("sensitivity_profile must decode to a JSON object")
    profile = _jsonable(parsed)
    if int(profile.get("schema_version", 0)) < 2:
        raise ValueError("Sensitivity profile schema_version must be >= 2")
    layers = profile.get("layers")
    if not isinstance(layers, Mapping) or not layers:
        raise ValueError("Sensitivity profile must contain a non-empty 'layers' object")

    schema_version = int(profile.get("schema_version", 0))
    for layer_key, row in layers.items():
        try:
            int(layer_key)
        except (TypeError, ValueError) as exc:
            raise ValueError(f"Invalid layer key: {layer_key!r}") from exc
        if not isinstance(row, Mapping):
            raise ValueError(f"Layer {layer_key} profile must be a JSON object")
        metric_row = row
        if schema_version >= 3:
            metadata = row.get("metadata", {})
            if not isinstance(metadata, Mapping):
                raise ValueError(f"Layer {layer_key} metadata must be a JSON object")
            metric_row = row.get("metrics")
            if not isinstance(metric_row, Mapping) or not metric_row:
                raise ValueError(f"Layer {layer_key} must contain non-empty metrics")
        for key, raw in metric_row.items():
            scalar = _extract_profile_scalar(raw, f"layers.{layer_key}.{key}")
            if not math.isfinite(scalar) or scalar <= 0.0:
                raise ValueError(
                    f"Sensitivity layers.{layer_key}.{key} must be finite and positive"
                )

    global_row = profile.get("global", {})
    if not isinstance(global_row, Mapping):
        raise ValueError("Sensitivity profile 'global' must be a JSON object")
    for key, raw in global_row.items():
        if key.endswith("_samples") or key in {"notes", "metadata"}:
            continue
        scalar = _extract_profile_scalar(raw, f"global.{key}")
        if not math.isfinite(scalar) or scalar <= 0.0:
            raise ValueError(f"Sensitivity global.{key} must be finite and positive")
    return dict(profile)


def sensitivity_profile_fingerprint(profile: Mapping[str, Any] | None) -> str | None:
    if profile is None:
        return None
    payload = json.dumps(_jsonable(profile), sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:16]


def _application_config(profile: Mapping[str, Any]) -> V2ApplicationConfig:
    raw = profile.get("application", {})
    if not isinstance(raw, Mapping):
        raise ValueError("Sensitivity profile 'application' must be a JSON object")
    config = V2ApplicationConfig(
        clip_min=float(raw.get("clip_min", 0.25)),
        clip_max=float(raw.get("clip_max", 4.0)),
        factor_clip_min=float(raw.get("factor_clip_min", 0.25)),
        factor_clip_max=float(raw.get("factor_clip_max", 4.0)),
        linear_policy=str(raw.get("linear_policy", "analytic")),
        strict_profile=bool(raw.get("strict_profile", True)),
        propagation_mode=str(raw.get("propagation_mode", "local_only")),
        local_normalization=str(raw.get("local_normalization", "per_block_median")),
        local_ratio_clip_min=float(raw.get("local_ratio_clip_min", 0.5)),
        local_ratio_clip_max=float(raw.get("local_ratio_clip_max", 2.0)),
        scale_normalization=str(raw.get("scale_normalization", "match_v1_median")),
        block_reconciliation=str(raw.get("block_reconciliation", "geometric")),
    )
    if not 0.0 < config.clip_min <= config.clip_max:
        raise ValueError("application clip_min/clip_max must satisfy 0 < min <= max")
    if not 0.0 < config.factor_clip_min <= config.factor_clip_max:
        raise ValueError("application factor clip must satisfy 0 < min <= max")
    if config.linear_policy not in {"analytic", "unit"}:
        raise ValueError("application.linear_policy must be analytic or unit")
    if config.propagation_mode != "local_only":
        raise ValueError(
            "Only propagation_mode='local_only' is supported by the corrected V2. "
            "Depth-wise sensitivity propagation was removed because it can be unstable."
        )
    if config.local_normalization != "per_block_median":
        raise ValueError("application.local_normalization must be per_block_median")
    if not 0.0 < config.local_ratio_clip_min <= 1.0:
        raise ValueError("local_ratio_clip_min must lie in (0, 1]")
    if config.local_ratio_clip_max < 1.0:
        raise ValueError("local_ratio_clip_max must be >= 1")
    # Hard guard against accidentally reintroducing an unsafe geometry.
    if config.local_ratio_clip_min < 0.25 or config.local_ratio_clip_max > 4.0:
        raise ValueError("Local V2/V1 ratio clip must stay within [0.25, 4.0]")
    return config


def _clamp(value: float, lower: float, upper: float) -> float:
    return min(max(float(value), float(lower)), float(upper))


def _profile_layer_value(
    profile: Mapping[str, Any],
    layer_index: int,
    key: str,
    config: V2ApplicationConfig,
    *,
    required: bool,
) -> Tuple[float, float, bool]:
    row = profile.get("layers", {}).get(str(layer_index))
    if row is None:
        if required and config.strict_profile:
            raise ValueError(f"Sensitivity profile has no layer {layer_index}")
        return 1.0, 1.0, False
    if int(profile.get("schema_version", 0)) >= 3:
        row = row.get("metrics", {})
    if key not in row:
        if required and config.strict_profile:
            raise ValueError(
                f"Sensitivity profile layer {layer_index} is missing {key!r}"
            )
        return 1.0, 1.0, False
    raw = _extract_profile_scalar(row[key], f"layers.{layer_index}.{key}")
    return raw, _clamp(raw, config.clip_min, config.clip_max), True


def _spectral_norm_power_iteration(
    matrix: torch.Tensor, power_iterations: int, eps: float = _EPS
) -> float:
    if matrix.ndim != 2:
        raise ValueError("Spectral norm requires a rank-2 matrix")
    if power_iterations < 1:
        raise ValueError("power_iterations must be >= 1")
    work = matrix.detach().float()
    rows, cols = work.shape
    if rows == 0 or cols == 0:
        return eps
    v = torch.ones(cols, device=work.device, dtype=work.dtype)
    v = v / torch.linalg.vector_norm(v).clamp_min(eps)
    for _ in range(power_iterations):
        u = torch.mv(work, v)
        u = u / torch.linalg.vector_norm(u).clamp_min(eps)
        v = torch.mv(work.transpose(0, 1), u)
        v = v / torch.linalg.vector_norm(v).clamp_min(eps)
    sigma = torch.linalg.vector_norm(torch.mv(work, v)).item()
    return max(float(sigma), eps)


def _rms_linear_sensitivity(weight: torch.Tensor, power_iterations: int) -> float:
    if weight.ndim != 2:
        return 1.0
    d_out, d_in = weight.shape
    if d_out <= 0 or d_in <= 0:
        return 1.0
    sigma = _spectral_norm_power_iteration(weight, power_iterations)
    return max(math.sqrt(float(d_in) / float(d_out)) * sigma, _EPS)


def _individual_linear_sensitivity(
    spec: ParameterSpec,
    parameter: torch.nn.Parameter,
    power_iterations: int,
    policy: str,
) -> float:
    if policy == "unit" or spec.group not in {"attention", "mlp"}:
        return 1.0
    if parameter.ndim == 2 and spec.name.endswith("weight"):
        return _rms_linear_sensitivity(parameter, power_iterations)
    return 1.0


def _stacked_linear_sensitivity(
    specs: Sequence[ParameterSpec],
    parameter_map: Mapping[str, torch.nn.Parameter],
    power_iterations: int,
    policy: str,
) -> float:
    if policy == "unit":
        return 1.0
    matrices = [
        parameter_map[spec.name]
        for spec in specs
        if parameter_map[spec.name].ndim == 2 and spec.name.endswith("weight")
    ]
    if not matrices:
        return 1.0
    if len(matrices) == 1:
        return _rms_linear_sensitivity(matrices[0], power_iterations)
    input_dims = {int(matrix.shape[1]) for matrix in matrices}
    if len(input_dims) != 1:
        return max(_rms_linear_sensitivity(m, power_iterations) for m in matrices)
    stacked = torch.cat([matrix.detach() for matrix in matrices], dim=0)
    value = _rms_linear_sensitivity(stacked, power_iterations)
    del stacked
    return value


def _atom(spec: ParameterSpec, mass: float, sensitivity: float = 1.0) -> ModuleNode:
    return ModuleNode(
        name=spec.logical_module,
        kind="atom",
        mass=float(mass),
        sensitivity=float(sensitivity),
        parameter_names=[spec.name],
        metadata={
            "group": spec.group,
            "role": spec.role,
            "layer_index": spec.layer_index,
            "shape": list(spec.shape),
            "multiplicity": float(spec.multiplicity),
            "input_sensitivity": float(sensitivity),
        },
    )


def _bond(name: str, sensitivity: float, metadata: Mapping[str, Any] | None = None) -> ModuleNode:
    return ModuleNode(
        name=name,
        kind="bond",
        mass=0.0,
        sensitivity=float(sensitivity),
        children=[],
        parameter_names=[],
        metadata=dict(metadata or {}),
    )


def _combine(
    kind: str,
    name: str,
    children: Sequence[ModuleNode],
    *,
    sensitivity_override: float | None = None,
    metadata: Mapping[str, Any] | None = None,
) -> ModuleNode:
    kept = [child for child in children if child.mass > 0.0 or child.kind == "bond"]
    mass = sum(child.mass for child in kept)
    if sensitivity_override is not None:
        sensitivity = float(sensitivity_override)
    elif kind == "compose":
        sensitivity = math.prod(child.sensitivity for child in kept) if kept else 1.0
    elif kind == "concat":
        sensitivity = sum(child.sensitivity for child in kept) if kept else 1.0
    elif kind == "residual":
        sensitivity = 1.0
    else:
        raise ValueError(f"Unsupported node kind: {kind}")
    return ModuleNode(
        name=name,
        kind=kind,
        mass=float(mass),
        sensitivity=float(sensitivity),
        children=kept,
        metadata=dict(metadata or {}),
    )


def _compose(name: str, children: Sequence[ModuleNode], **kwargs: Any) -> ModuleNode:
    return _combine("compose", name, children, **kwargs)


def _concat(name: str, children: Sequence[ModuleNode], **kwargs: Any) -> ModuleNode:
    return _combine("concat", name, children, **kwargs)


def _residual(name: str, branch: ModuleNode, metadata: Mapping[str, Any] | None = None) -> ModuleNode:
    payload = {
        "sensitivity_proxy": "unit_local_only",
        "measured_residual_is_diagnostic_only": True,
    }
    payload.update(dict(metadata or {}))
    return _combine(
        "residual",
        name,
        [branch],
        sensitivity_override=1.0,
        metadata=payload,
    )


def _propagate_scales(
    node: ModuleNode,
    incoming_scale: float,
    output: MutableMapping[str, float],
) -> None:
    if node.kind == "atom":
        for name in node.parameter_names:
            if name in output:
                raise ValueError(f"Parameter {name!r} appears multiple times in V2 tree")
            output[name] = float(incoming_scale)
        return
    if node.kind == "bond":
        return
    children = [child for child in node.children if child.mass > 0.0 or child.kind == "bond"]
    if node.kind == "compose":
        for index, child in enumerate(children):
            if child.mass <= 0.0:
                continue
            downstream = math.prod(later.sensitivity for later in children[index + 1 :])
            _propagate_scales(
                child,
                incoming_scale * downstream * node.mass / child.mass,
                output,
            )
        return
    if node.kind in {"concat", "residual"}:
        for child in children:
            if child.mass <= 0.0:
                continue
            _propagate_scales(child, incoming_scale * node.mass / child.mass, output)
        return
    raise ValueError(f"Unsupported V2 node kind: {node.kind}")


def _nodes_for_specs(
    specs: Sequence[ParameterSpec],
    assigned_masses: Mapping[str, float],
    sensitivities: Mapping[str, float],
) -> List[ModuleNode]:
    return [
        _atom(spec, assigned_masses[spec.name], sensitivities.get(spec.name, 1.0))
        for spec in specs
        if assigned_masses[spec.name] > 0.0
    ]


def _factorized_bond_sensitivity(
    measured_module: float,
    upstream_linear: float,
    downstream_linear: float,
    config: V2ApplicationConfig,
) -> Tuple[float, float]:
    raw = measured_module / max(upstream_linear * downstream_linear, _EPS)
    return raw, _clamp(raw, config.factor_clip_min, config.factor_clip_max)


def _finite_median(values: Iterable[float]) -> float:
    rows = [float(v) for v in values if math.isfinite(float(v)) and float(v) > 0.0]
    if not rows:
        raise ValueError("No positive finite values")
    return float(statistics.median(rows))


def _finite_summary(values: Iterable[float]) -> Dict[str, float | int | None]:
    rows = [float(v) for v in values if math.isfinite(float(v))]
    if not rows:
        return {"count": 0, "min": None, "median": None, "max": None}
    return {
        "count": len(rows),
        "min": min(rows),
        "median": statistics.median(rows),
        "max": max(rows),
    }


def _build_olmo3_local_only_tree(
    specs: Sequence[ParameterSpec],
    assigned_masses: Mapping[str, float],
    parameter_map: Mapping[str, torch.nn.Parameter],
    profile: Mapping[str, Any],
    power_iterations: int,
    config: V2ApplicationConfig,
) -> Tuple[ModuleNode, Dict[str, Any], Dict[str, float], Dict[str, float]]:
    """Build an OLMo3/Gemma3 branch-post-norm shadow tree.

    OLMo3 has no input pre-norm. Q/K norms live inside attention, while the
    attention and MLP output norms are applied before their residual additions.
    """

    architecture = str(profile.get("architecture", {}).get("family", "olmo3"))
    is_gemma3 = architecture == "gemma3"
    layer_ids = sorted({spec.layer_index for spec in specs if spec.layer_index is not None})
    sensitivity_raw: Dict[str, float] = {}
    sensitivity_used: Dict[str, float] = {}
    for spec in specs:
        raw = _individual_linear_sensitivity(
            spec, parameter_map[spec.name], power_iterations, config.linear_policy
        )
        sensitivity_raw[spec.name] = raw
        sensitivity_used[spec.name] = _clamp(raw, config.clip_min, config.clip_max)

    embedding_specs = [spec for spec in specs if spec.group == "embedding"]
    head_specs = [spec for spec in specs if spec.group == "head"]
    final_norm_specs = [spec for spec in specs if spec.role == "final_norm"]
    embedding_nodes = _nodes_for_specs(embedding_specs, assigned_masses, {})
    head_nodes = _nodes_for_specs(head_specs, assigned_masses, {})
    final_norm_nodes = _nodes_for_specs(final_norm_specs, assigned_masses, {})
    consumed = {
        node.parameter_names[0]
        for node in embedding_nodes + head_nodes + final_norm_nodes
        if node.parameter_names
    }
    block_nodes: List[ModuleNode] = []
    layer_diagnostics: Dict[str, Any] = {}
    required = (
        "q_norm",
        "k_norm",
        "attention_module",
        "attention_output_norm",
        "mlp_module",
        "mlp_output_norm",
    )
    if is_gemma3:
        required += ("input_norm", "pre_feedforward_norm")
    diagnostic = ("attention_residual", "mlp_residual", "block")

    for layer_id in layer_ids:
        layer_specs = [spec for spec in specs if spec.layer_index == layer_id]
        attention_specs = [spec for spec in layer_specs if spec.group == "attention"]
        mlp_specs = [spec for spec in layer_specs if spec.group == "mlp"]
        q_norm_specs = [spec for spec in layer_specs if spec.role == "q_norm"]
        k_norm_specs = [spec for spec in layer_specs if spec.role == "k_norm"]
        attention_output_norm_specs = [
            spec for spec in layer_specs if spec.role == "attention_output_norm"
        ]
        mlp_output_norm_specs = [
            spec for spec in layer_specs if spec.role == "mlp_output_norm"
        ]
        input_norm_specs = [spec for spec in layer_specs if spec.role == "input_norm"]
        pre_feedforward_norm_specs = [
            spec for spec in layer_specs if spec.role == "pre_feedforward_norm"
        ]

        profile_raw: Dict[str, float] = {}
        profile_used: Dict[str, float] = {}
        profile_present: Dict[str, bool] = {}
        for key in required + diagnostic:
            raw, used, present = _profile_layer_value(
                profile, layer_id, key, config, required=key in required
            )
            profile_raw[key] = raw
            profile_used[key] = used
            profile_present[key] = present
        for spec in q_norm_specs:
            sensitivity_raw[spec.name] = profile_raw["q_norm"]
            sensitivity_used[spec.name] = profile_used["q_norm"]
        for spec in k_norm_specs:
            sensitivity_raw[spec.name] = profile_raw["k_norm"]
            sensitivity_used[spec.name] = profile_used["k_norm"]
        for spec in attention_output_norm_specs:
            sensitivity_raw[spec.name] = profile_raw["attention_output_norm"]
            sensitivity_used[spec.name] = profile_used["attention_output_norm"]
        for spec in mlp_output_norm_specs:
            sensitivity_raw[spec.name] = profile_raw["mlp_output_norm"]
            sensitivity_used[spec.name] = profile_used["mlp_output_norm"]
        for spec in input_norm_specs:
            sensitivity_raw[spec.name] = profile_raw["input_norm"]
            sensitivity_used[spec.name] = profile_used["input_norm"]
        for spec in pre_feedforward_norm_specs:
            sensitivity_raw[spec.name] = profile_raw["pre_feedforward_norm"]
            sensitivity_used[spec.name] = profile_used["pre_feedforward_norm"]

        qkv_specs = [
            spec for spec in attention_specs
            if spec.role in {"q", "k", "v", "qkv", "attention_other"}
        ]
        o_specs = [spec for spec in attention_specs if spec.role == "o"]
        qkv_raw = _stacked_linear_sensitivity(
            qkv_specs, parameter_map, power_iterations, config.linear_policy
        )
        qkv_used = _clamp(qkv_raw, config.clip_min, config.clip_max)
        o_raw = _stacked_linear_sensitivity(
            o_specs, parameter_map, power_iterations, config.linear_policy
        )
        o_used = _clamp(o_raw, config.clip_min, config.clip_max)
        qk_norm_used = max(profile_used["q_norm"], profile_used["k_norm"])
        qkv_parallel = _concat(
            f"layer_{layer_id}.qkv_parallel",
            _nodes_for_specs(qkv_specs, assigned_masses, sensitivity_used),
            sensitivity_override=qkv_used,
        )
        qk_norm = _concat(
            f"layer_{layer_id}.qk_norms",
            _nodes_for_specs(
                q_norm_specs + k_norm_specs, assigned_masses, sensitivity_used
            ),
            sensitivity_override=qk_norm_used,
        )
        o_projection = _concat(
            f"layer_{layer_id}.o_projection",
            _nodes_for_specs(o_specs, assigned_masses, sensitivity_used),
            sensitivity_override=o_used if o_specs else 1.0,
        )
        attn_core_raw, attn_core_used = _factorized_bond_sensitivity(
            profile_used["attention_module"],
            qkv_used * qk_norm_used,
            o_used,
            config,
        )
        attention_output_norm = _concat(
            f"layer_{layer_id}.attention_output_norm",
            _nodes_for_specs(
                attention_output_norm_specs, assigned_masses, sensitivity_used
            ),
            sensitivity_override=profile_used["attention_output_norm"],
        )
        input_norm = _concat(
            f"layer_{layer_id}.input_norm",
            _nodes_for_specs(input_norm_specs, assigned_masses, sensitivity_used),
            sensitivity_override=profile_used.get("input_norm", 1.0),
        )
        attention_components = []
        if input_norm_specs:
            attention_components.append(input_norm)
        attention_components.extend([
            qkv_parallel,
            qk_norm,
            _bond(f"layer_{layer_id}.functional_attention", attn_core_used),
            o_projection,
            attention_output_norm,
        ])
        attention_branch = _compose(
            f"layer_{layer_id}.attention_branch",
            attention_components,
        )
        attention_residual = _residual(
            f"layer_{layer_id}.attention_residual",
            attention_branch,
            {"measured_raw": profile_raw["attention_residual"]},
        )

        gate_up_specs = [
            spec for spec in mlp_specs
            if spec.role in {"gate", "up", "gate_up", "mlp_other"}
        ]
        down_specs = [spec for spec in mlp_specs if spec.role == "down"]
        gate_up_raw = _stacked_linear_sensitivity(
            gate_up_specs, parameter_map, power_iterations, config.linear_policy
        )
        gate_up_used = _clamp(gate_up_raw, config.clip_min, config.clip_max)
        down_raw = _stacked_linear_sensitivity(
            down_specs, parameter_map, power_iterations, config.linear_policy
        )
        down_used = _clamp(down_raw, config.clip_min, config.clip_max)
        swiglu_raw, swiglu_used = _factorized_bond_sensitivity(
            profile_used["mlp_module"], gate_up_used, down_used, config
        )
        gate_up_parallel = _concat(
            f"layer_{layer_id}.gate_up_parallel",
            _nodes_for_specs(gate_up_specs, assigned_masses, sensitivity_used),
            sensitivity_override=gate_up_used,
        )
        down_projection = _concat(
            f"layer_{layer_id}.down_projection",
            _nodes_for_specs(down_specs, assigned_masses, sensitivity_used),
            sensitivity_override=down_used if down_specs else 1.0,
        )
        mlp_output_norm = _concat(
            f"layer_{layer_id}.mlp_output_norm",
            _nodes_for_specs(mlp_output_norm_specs, assigned_masses, sensitivity_used),
            sensitivity_override=profile_used["mlp_output_norm"],
        )
        pre_feedforward_norm = _concat(
            f"layer_{layer_id}.pre_feedforward_norm",
            _nodes_for_specs(
                pre_feedforward_norm_specs, assigned_masses, sensitivity_used
            ),
            sensitivity_override=profile_used.get("pre_feedforward_norm", 1.0),
        )
        mlp_components = []
        if pre_feedforward_norm_specs:
            mlp_components.append(pre_feedforward_norm)
        mlp_components.extend([
            gate_up_parallel,
            _bond(f"layer_{layer_id}.swiglu", swiglu_used),
            down_projection,
            mlp_output_norm,
        ])
        mlp_branch = _compose(
            f"layer_{layer_id}.mlp_branch",
            mlp_components,
        )
        mlp_residual = _residual(
            f"layer_{layer_id}.mlp_residual",
            mlp_branch,
            {"measured_raw": profile_raw["mlp_residual"]},
        )
        block = _compose(
            f"layer_{layer_id}.block",
            [attention_residual, mlp_residual],
            sensitivity_override=1.0,
            metadata={
                "block_layout": "branch_post_norm",
                "measured_block_sensitivity_raw": profile_raw["block"],
                "exported_sensitivity": 1.0,
            },
        )
        if block.mass > 0.0:
            block_nodes.append(block)
        consumed.update(
            spec.name
            for spec in (
                attention_specs
                + mlp_specs
                + q_norm_specs
                + k_norm_specs
                + attention_output_norm_specs
                + mlp_output_norm_specs
                + input_norm_specs
                + pre_feedforward_norm_specs
            )
        )
        layer_diagnostics[str(layer_id)] = {
            "architecture_family": architecture,
            "profile_raw": profile_raw,
            "profile_used_locally": profile_used,
            "profile_present": profile_present,
            "qkv_linear_sensitivity_raw": qkv_raw,
            "qkv_linear_sensitivity_used": qkv_used,
            "o_linear_sensitivity_raw": o_raw,
            "o_linear_sensitivity_used": o_used,
            "attention_core_factor_raw": attn_core_raw,
            "attention_core_factor_used": attn_core_used,
            "gate_up_linear_sensitivity_raw": gate_up_raw,
            "gate_up_linear_sensitivity_used": gate_up_used,
            "down_linear_sensitivity_raw": down_raw,
            "down_linear_sensitivity_used": down_used,
            "swiglu_factor_raw": swiglu_raw,
            "swiglu_factor_used": swiglu_used,
            "attention_branch_sensitivity": attention_branch.sensitivity,
            "mlp_branch_sensitivity": mlp_branch.sensitivity,
            "exported_block_sensitivity": 1.0,
            "residual_and_block_metrics_are_diagnostic_only": True,
        }

    fallback_specs = [
        spec for spec in specs
        if spec.name not in consumed and assigned_masses[spec.name] > 0.0
    ]
    ordered: List[ModuleNode] = []
    if embedding_nodes:
        ordered.append(_concat("token_embedding", embedding_nodes, sensitivity_override=1.0))
    ordered.extend(block_nodes)
    if final_norm_nodes:
        ordered.append(_concat("final_norm", final_norm_nodes, sensitivity_override=1.0))
    if head_nodes:
        ordered.append(_concat("lm_head", head_nodes, sensitivity_override=1.0))
    if fallback_specs:
        ordered.append(
            _concat(
                "structural_fallback_parameters",
                _nodes_for_specs(fallback_specs, assigned_masses, {}),
                sensitivity_override=1.0,
            )
        )
    root = _compose(
        f"{architecture}_recursive_modular_v2_local_only",
        ordered,
        sensitivity_override=1.0,
        metadata={
            "version": "2.1-localfix",
            "architecture_family": architecture,
            "block_layout": (
                "pre_norm_branch_post_norm" if is_gemma3 else "branch_post_norm"
            ),
        },
    )
    if root.mass <= 0.0:
        raise ValueError("Recursive modular OLMo3 tree has zero active mass")
    return root, layer_diagnostics, sensitivity_used, sensitivity_raw


def _build_local_only_tree(
    specs: Sequence[ParameterSpec],
    assigned_masses: Mapping[str, float],
    parameter_map: Mapping[str, torch.nn.Parameter],
    profile: Mapping[str, Any],
    power_iterations: int,
    config: V2ApplicationConfig,
) -> Tuple[ModuleNode, Dict[str, Any], Dict[str, float], Dict[str, float]]:
    by_name = {spec.name: spec for spec in specs}
    layer_ids = sorted({spec.layer_index for spec in specs if spec.layer_index is not None})

    sensitivity_raw: Dict[str, float] = {}
    sensitivity_used: Dict[str, float] = {}
    for spec in specs:
        raw = _individual_linear_sensitivity(
            spec, parameter_map[spec.name], power_iterations, config.linear_policy
        )
        sensitivity_raw[spec.name] = raw
        sensitivity_used[spec.name] = _clamp(raw, config.clip_min, config.clip_max)

    embedding_specs = [spec for spec in specs if spec.group == "embedding"]
    head_specs = [spec for spec in specs if spec.group == "head"]
    final_norm_specs = [spec for spec in specs if spec.role == "final_norm"]

    # Non-block modules intentionally remain exactly V1-like.
    embedding_nodes = _nodes_for_specs(embedding_specs, assigned_masses, {})
    head_nodes = _nodes_for_specs(head_specs, assigned_masses, {})
    final_norm_nodes = _nodes_for_specs(final_norm_specs, assigned_masses, {})
    consumed = {
        node.parameter_names[0]
        for node in embedding_nodes + head_nodes + final_norm_nodes
        if node.parameter_names
    }

    block_nodes: List[ModuleNode] = []
    layer_diagnostics: Dict[str, Any] = {}

    for layer_id in layer_ids:
        layer_specs = [spec for spec in specs if spec.layer_index == layer_id]
        input_norm_specs = [spec for spec in layer_specs if spec.role == "input_norm"]
        post_norm_specs = [
            spec for spec in layer_specs if spec.role == "post_attention_norm"
        ]
        attention_specs = [spec for spec in layer_specs if spec.group == "attention"]
        mlp_specs = [spec for spec in layer_specs if spec.group == "mlp"]

        profile_raw: Dict[str, float] = {}
        profile_used: Dict[str, float] = {}
        profile_present: Dict[str, bool] = {}
        for key in _LOCAL_REQUIRED_LAYER_KEYS + _DIAGNOSTIC_LAYER_KEYS:
            raw, used, present = _profile_layer_value(
                profile,
                layer_id,
                key,
                config,
                required=key in _LOCAL_REQUIRED_LAYER_KEYS,
            )
            profile_raw[key] = raw
            profile_used[key] = used
            profile_present[key] = present

        for spec in input_norm_specs:
            sensitivity_raw[spec.name] = profile_raw["input_norm"]
            sensitivity_used[spec.name] = profile_used["input_norm"]
        for spec in post_norm_specs:
            sensitivity_raw[spec.name] = profile_raw["post_attention_norm"]
            sensitivity_used[spec.name] = profile_used["post_attention_norm"]

        input_norm = _concat(
            f"layer_{layer_id}.input_norm",
            _nodes_for_specs(input_norm_specs, assigned_masses, sensitivity_used),
            sensitivity_override=profile_used["input_norm"],
        )

        qkv_specs = [
            spec
            for spec in attention_specs
            if spec.role in {"q", "k", "v", "qkv", "attention_other"}
        ]
        o_specs = [spec for spec in attention_specs if spec.role == "o"]
        qkv_raw = _stacked_linear_sensitivity(
            qkv_specs, parameter_map, power_iterations, config.linear_policy
        )
        qkv_used = _clamp(qkv_raw, config.clip_min, config.clip_max)
        o_raw = _stacked_linear_sensitivity(
            o_specs, parameter_map, power_iterations, config.linear_policy
        )
        o_used = _clamp(o_raw, config.clip_min, config.clip_max)
        qkv_parallel = _concat(
            f"layer_{layer_id}.qkv_parallel",
            _nodes_for_specs(qkv_specs, assigned_masses, sensitivity_used),
            sensitivity_override=qkv_used,
        )
        o_projection = _concat(
            f"layer_{layer_id}.o_projection",
            _nodes_for_specs(o_specs, assigned_masses, sensitivity_used),
            sensitivity_override=o_used if o_specs else 1.0,
        )
        attn_core_raw, attn_core_used = _factorized_bond_sensitivity(
            profile_used["attention_module"], qkv_used, o_used, config
        )
        attention_branch = _compose(
            f"layer_{layer_id}.attention_branch",
            [
                input_norm,
                qkv_parallel,
                _bond(
                    f"layer_{layer_id}.functional_attention",
                    attn_core_used,
                    {
                        "raw_factorized_sensitivity": attn_core_raw,
                        "used_factorized_sensitivity": attn_core_used,
                    },
                ),
                o_projection,
            ],
        )
        attention_residual = _residual(
            f"layer_{layer_id}.attention_residual",
            attention_branch,
            {
                "measured_raw": profile_raw["attention_residual"],
                "measured_used_for_propagation": False,
            },
        )

        post_norm = _concat(
            f"layer_{layer_id}.post_attention_norm",
            _nodes_for_specs(post_norm_specs, assigned_masses, sensitivity_used),
            sensitivity_override=profile_used["post_attention_norm"],
        )
        gate_up_specs = [
            spec
            for spec in mlp_specs
            if spec.role in {"gate", "up", "gate_up", "mlp_other"}
        ]
        down_specs = [spec for spec in mlp_specs if spec.role == "down"]
        gate_up_raw = _stacked_linear_sensitivity(
            gate_up_specs, parameter_map, power_iterations, config.linear_policy
        )
        gate_up_used = _clamp(gate_up_raw, config.clip_min, config.clip_max)
        down_raw = _stacked_linear_sensitivity(
            down_specs, parameter_map, power_iterations, config.linear_policy
        )
        down_used = _clamp(down_raw, config.clip_min, config.clip_max)
        gate_up_parallel = _concat(
            f"layer_{layer_id}.gate_up_parallel",
            _nodes_for_specs(gate_up_specs, assigned_masses, sensitivity_used),
            sensitivity_override=gate_up_used,
        )
        down_projection = _concat(
            f"layer_{layer_id}.down_projection",
            _nodes_for_specs(down_specs, assigned_masses, sensitivity_used),
            sensitivity_override=down_used if down_specs else 1.0,
        )
        swiglu_raw, swiglu_used = _factorized_bond_sensitivity(
            profile_used["mlp_module"], gate_up_used, down_used, config
        )
        mlp_branch = _compose(
            f"layer_{layer_id}.mlp_branch",
            [
                post_norm,
                gate_up_parallel,
                _bond(
                    f"layer_{layer_id}.swiglu",
                    swiglu_used,
                    {
                        "raw_factorized_sensitivity": swiglu_raw,
                        "used_factorized_sensitivity": swiglu_used,
                    },
                ),
                down_projection,
            ],
        )
        mlp_residual = _residual(
            f"layer_{layer_id}.mlp_residual",
            mlp_branch,
            {
                "measured_raw": profile_raw["mlp_residual"],
                "measured_used_for_propagation": False,
            },
        )

        # Critical safety property: the block exports sensitivity one.  The MLP
        # residual also exports one, so attention parameters do not receive a
        # measured MLP-residual multiplier.
        block = _compose(
            f"layer_{layer_id}.block",
            [attention_residual, mlp_residual],
            sensitivity_override=1.0,
            metadata={
                "measured_block_sensitivity_raw": profile_raw["block"],
                "measured_block_used_for_propagation": False,
                "exported_sensitivity": 1.0,
            },
        )
        if block.mass > 0.0:
            block_nodes.append(block)

        consumed.update(spec.name for spec in input_norm_specs)
        consumed.update(spec.name for spec in post_norm_specs)
        consumed.update(spec.name for spec in attention_specs)
        consumed.update(spec.name for spec in mlp_specs)
        layer_diagnostics[str(layer_id)] = {
            "profile_raw": profile_raw,
            "profile_used_locally": profile_used,
            "profile_present": profile_present,
            "qkv_linear_sensitivity_raw": qkv_raw,
            "qkv_linear_sensitivity_used": qkv_used,
            "o_linear_sensitivity_raw": o_raw,
            "o_linear_sensitivity_used": o_used,
            "attention_core_factor_raw": attn_core_raw,
            "attention_core_factor_used": attn_core_used,
            "gate_up_linear_sensitivity_raw": gate_up_raw,
            "gate_up_linear_sensitivity_used": gate_up_used,
            "down_linear_sensitivity_raw": down_raw,
            "down_linear_sensitivity_used": down_used,
            "swiglu_factor_raw": swiglu_raw,
            "swiglu_factor_used": swiglu_used,
            "attention_branch_sensitivity": attention_branch.sensitivity,
            "mlp_branch_sensitivity": mlp_branch.sensitivity,
            "exported_block_sensitivity": 1.0,
            "residual_and_block_metrics_are_diagnostic_only": True,
        }

    fallback_specs = [
        spec
        for spec in specs
        if spec.name not in consumed and assigned_masses[spec.name] > 0.0
    ]
    fallback_nodes = _nodes_for_specs(fallback_specs, assigned_masses, {})

    ordered: List[ModuleNode] = []
    if embedding_nodes:
        ordered.append(_concat("token_embedding", embedding_nodes, sensitivity_override=1.0))
    ordered.extend(block_nodes)
    if final_norm_nodes:
        ordered.append(_concat("final_norm", final_norm_nodes, sensitivity_override=1.0))
    if head_nodes:
        ordered.append(_concat("lm_head", head_nodes, sensitivity_override=1.0))
    if fallback_nodes:
        ordered.append(
            _concat(
                "structural_fallback_parameters",
                fallback_nodes,
                sensitivity_override=1.0,
            )
        )

    architecture = str(profile.get("architecture", {}).get("family", "qwen2"))
    root = _compose(
        f"{architecture}_recursive_modular_v2_local_only",
        ordered,
        sensitivity_override=1.0,
        metadata={
            "version": "2.1-localfix",
            "profile_fingerprint": sensitivity_profile_fingerprint(profile),
            "propagation_mode": "local_only",
        },
    )
    if root.mass <= 0.0:
        raise ValueError("Recursive modular V2 tree has zero active mass")
    return root, layer_diagnostics, sensitivity_used, sensitivity_raw


def build_recursive_modular_result_v2(
    named_parameters: Iterable[Tuple[str, torch.nn.Parameter]],
    mass_config: Mapping[str, float],
    sensitivity_profile: Mapping[str, Any] | str,
    power_iterations: int = 8,
) -> RecursiveModularResult:
    """Build safe, local-only V2 scales for a supported decoder worker."""

    profile = load_sensitivity_profile(sensitivity_profile)
    if profile is None:
        raise ValueError("recursive_modular_shell_v2 requires a sensitivity profile")
    config = _application_config(profile)
    architecture_row = profile.get("architecture", {})
    if not isinstance(architecture_row, Mapping):
        raise ValueError("Sensitivity profile 'architecture' must be a JSON object")
    architecture = str(architecture_row.get("family", "qwen2"))
    if architecture not in {"qwen2", "llama", "olmo3", "gemma3"}:
        raise ValueError(f"Unsupported profile architecture family: {architecture!r}")
    pairs = list(named_parameters)
    if not pairs:
        raise ValueError("No perturbable parameters were provided")
    parameter_map = {name: param for name, param in pairs}
    specs_list = [
        infer_parameter_spec(name, tuple(param.shape), architecture)
        for name, param in pairs
    ]
    fallback_roles = {
        "other",
        "attention_other",
        "mlp_other",
        "layer_norm_other",
        "norm_other",
    }
    unclassified = [
        spec.name for spec in specs_list if spec.role in fallback_roles
    ]
    if int(profile.get("schema_version", 0)) >= 3 and unclassified:
        preview = ", ".join(repr(name) for name in unclassified[:10])
        suffix = " ..." if len(unclassified) > 10 else ""
        raise ValueError(
            "Schema-v3 runtime requires every perturbable tensor to have one "
            f"semantic role; unclassified: {preview}{suffix}"
        )
    specs = {spec.name: spec for spec in specs_list}
    detected_layers = sorted(
        {spec.layer_index for spec in specs_list if spec.layer_index is not None}
    )
    profile_layers = sorted(int(key) for key in profile["layers"])
    if config.strict_profile and detected_layers != profile_layers:
        raise ValueError(
            "Sensitivity profile layers do not match worker layers: "
            f"worker={detected_layers}, profile={profile_layers}"
        )

    assigned_masses = _allocate_masses(specs_list, mass_config)
    v1 = build_recursive_modular_result(pairs, mass_config, architecture=architecture)
    tree_builder = (
        _build_olmo3_local_only_tree
        if architecture in {"olmo3", "gemma3"}
        else _build_local_only_tree
    )
    tree, layer_diagnostics, parameter_sensitivities, parameter_sensitivities_raw = (
        tree_builder(
            specs_list,
            assigned_masses,
            parameter_map,
            profile,
            power_iterations,
            config,
        )
    )

    local_raw_scales: Dict[str, float] = {}
    _propagate_scales(tree, 1.0, local_raw_scales)

    raw_ratios: Dict[str, float] = {}
    final_ratios: Dict[str, float] = {}
    layer_ratio_diagnostics: Dict[str, Any] = {}

    # Only layer-local parameters receive calibrated corrections.  All global
    # components stay exactly at their V1 scale.
    for layer_id in detected_layers:
        names = [
            spec.name
            for spec in specs_list
            if spec.layer_index == layer_id
            and assigned_masses.get(spec.name, 0.0) > 0.0
        ]
        ratios = []
        for name in names:
            raw = local_raw_scales[name] / v1.scales[name]
            if not math.isfinite(raw) or raw <= 0.0:
                raise RuntimeError(f"Invalid local V2/V1 ratio for {name!r}: {raw}")
            raw_ratios[name] = raw
            ratios.append(raw)
        center = _finite_median(ratios) if ratios else 1.0
        clipped_rows = []
        for name in names:
            centered = raw_ratios[name] / center
            used = _clamp(
                centered,
                config.local_ratio_clip_min,
                config.local_ratio_clip_max,
            )
            final_ratios[name] = used
            clipped_rows.append(used)
        layer_ratio_diagnostics[str(layer_id)] = {
            "raw_ratio_summary": _finite_summary(ratios),
            "centering_median": center,
            "final_ratio_summary": _finite_summary(clipped_rows),
            "num_parameters": len(names),
        }

    for spec in specs_list:
        if assigned_masses.get(spec.name, 0.0) <= 0.0:
            continue
        if spec.name not in final_ratios:
            raw_ratios[spec.name] = 1.0
            final_ratios[spec.name] = 1.0

    scales: Dict[str, float] = {}
    parameter_rows: List[Dict[str, Any]] = []
    for spec in specs_list:
        mass = float(assigned_masses.get(spec.name, 0.0))
        if mass <= 0.0:
            scales[spec.name] = float("inf")
            ratio: float | str = "inf"
        else:
            ratio_value = final_ratios[spec.name]
            scale = float(v1.scales[spec.name]) * ratio_value
            if not math.isfinite(scale) or scale <= 0.0:
                raise RuntimeError(f"Invalid corrected V2 scale for {spec.name!r}: {scale}")
            scales[spec.name] = scale
            ratio = ratio_value
        parameter_rows.append(
            {
                "parameter_name": spec.name,
                "shape": list(spec.shape),
                "group": spec.group,
                "role": spec.role,
                "logical_module": spec.logical_module,
                "layer_index": spec.layer_index,
                "multiplicity": float(spec.multiplicity),
                "assigned_mass": mass,
                "input_sensitivity_raw": float(
                    parameter_sensitivities_raw.get(spec.name, 1.0)
                ),
                "input_sensitivity_used_locally": float(
                    parameter_sensitivities.get(spec.name, 1.0)
                ),
                "v1_scale": (
                    float(v1.scales[spec.name])
                    if math.isfinite(v1.scales[spec.name])
                    else "inf"
                ),
                "raw_local_v2_to_v1_ratio": (
                    float(raw_ratios.get(spec.name, 1.0)) if mass > 0.0 else "inf"
                ),
                "final_v2_to_v1_ratio": ratio,
                "scale": float(scales[spec.name]) if math.isfinite(scales[spec.name]) else "inf",
            }
        )

    active_ratios = [
        final_ratios[name]
        for name, mass in assigned_masses.items()
        if mass > 0.0
    ]
    ratio_summary = _finite_summary(active_ratios)
    ratio_min = float(ratio_summary["min"])
    ratio_max = float(ratio_summary["max"])
    tolerance = 1e-9
    if ratio_min < config.local_ratio_clip_min - tolerance or ratio_max > config.local_ratio_clip_max + tolerance:
        raise RuntimeError(
            "Corrected V2 scale ratios escaped the configured safety interval: "
            f"[{ratio_min}, {ratio_max}]"
        )

    group_statistics: Dict[str, Any] = {}
    for group in mass_config:
        names = [spec.name for spec in specs_list if spec.group == group]
        group_statistics[group] = {
            "configured_mass": float(mass_config[group]),
            "present_parameter_count": len(names),
            "active_parameter_count": sum(
                assigned_masses.get(name, 0.0) > 0.0 for name in names
            ),
            "assigned_mass_sum": float(
                sum(assigned_masses.get(name, 0.0) for name in names)
            ),
            "scale_summary": _finite_summary(scales[name] for name in names),
            "v2_to_v1_ratio_summary": _finite_summary(
                final_ratios[name]
                for name in names
                if assigned_masses.get(name, 0.0) > 0.0
            ),
        }

    diagnostics = {
        "method": "recursive_modular_shell_v2",
        "version": "2.1-localfix",
        "description": (
            "V1 architecture/mass geometry with sensitivity-calibrated, "
            "per-block local scale corrections"
        ),
        "profile_fingerprint": sensitivity_profile_fingerprint(profile),
        "profile_model_name": profile.get("model_name"),
        "architecture_family": architecture,
        "application": {
            "propagation_mode": config.propagation_mode,
            "local_normalization": config.local_normalization,
            "local_ratio_clip_min": config.local_ratio_clip_min,
            "local_ratio_clip_max": config.local_ratio_clip_max,
            "clip_min": config.clip_min,
            "clip_max": config.clip_max,
            "factor_clip_min": config.factor_clip_min,
            "factor_clip_max": config.factor_clip_max,
            "linear_policy": config.linear_policy,
            "strict_profile": config.strict_profile,
            "legacy_scale_normalization_ignored": config.scale_normalization,
            "legacy_block_reconciliation_ignored": config.block_reconciliation,
        },
        # V2.1 centers corrections independently inside every decoder layer;
        # there is deliberately no additional whole-model rescaling.  Keep
        # this legacy diagnostics field so the baseline worker interface can
        # report the value without changing official RandOpt worker behavior.
        "normalization_factor": 1.0,
        "normalization_reference": {
            "policy": "layer_local_median_centering",
        },
        "root_mass": float(tree.mass),
        "root_sensitivity": float(tree.sensitivity),
        "num_parameters": len(specs_list),
        "num_unclassified_parameters": len(unclassified),
        "num_active_parameters": sum(v > 0.0 for v in assigned_masses.values()),
        "num_layers_detected": len(detected_layers),
        "mass_config": {key: float(value) for key, value in mass_config.items()},
        "scale_statistics": _finite_summary(scales.values()),
        "v1_scale_statistics": _finite_summary(v1.scales.values()),
        "v2_to_v1_ratio_statistics": ratio_summary,
        "group_statistics": group_statistics,
        "layer_sensitivities": layer_diagnostics,
        "layer_ratio_diagnostics": layer_ratio_diagnostics,
        "parameters": parameter_rows,
        "tree": tree.to_dict(),
        "safety_checks": {
            "no_depthwise_sensitivity_product": True,
            "all_exported_block_sensitivities_are_one": all(
                row["exported_block_sensitivity"] == 1.0
                for row in layer_diagnostics.values()
            ),
            "final_ratio_within_bounds": True,
            "global_modules_equal_v1": all(
                math.isclose(final_ratios.get(spec.name, 1.0), 1.0)
                for spec in specs_list
                if spec.layer_index is None
                and assigned_masses.get(spec.name, 0.0) > 0.0
            ),
        },
        "assumptions": [
            f"{architecture} forward pass is unchanged.",
            "The sensitivity profile is fixed before candidate sampling.",
            "Measured residual and full-block Jacobians are diagnostics only.",
            "Sensitivity corrections are median-centered independently inside each block.",
            "Final V2/V1 scale ratios are clipped to a bounded interval.",
        ],
    }

    return RecursiveModularResult(
        scales=scales,
        assigned_masses=assigned_masses,
        specs=specs,
        tree=tree,
        diagnostics=diagnostics,
    )


def build_recursive_modular_scales_v2(
    named_parameters: Iterable[Tuple[str, torch.nn.Parameter]],
    mass_config: Mapping[str, float],
    sensitivity_profile: Mapping[str, Any] | str,
    power_iterations: int = 8,
) -> Dict[str, float]:
    return build_recursive_modular_result_v2(
        named_parameters,
        mass_config,
        sensitivity_profile,
        power_iterations,
    ).scales
